[project]
name = 'counter'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.asserts]
path = 'contracts/asserts.clar'
clarity_version = 2
epoch = 2.4

[contracts.asserts1]
path = 'contracts/asserts1.clar'
clarity_version = 2
epoch = 2.4

[contracts.basics]
path = 'contracts/basics.clar'
clarity_version = 2
epoch = 2.4

[contracts.composite]
path = 'contracts/composite.clar'
clarity_version = 2
epoch = 2.4

[contracts.constant]
path = 'contracts/constant.clar'
clarity_version = 2
epoch = 2.4

[contracts.controlflow]
path = 'contracts/controlflow.clar'
clarity_version = 2
epoch = 2.4

[contracts.counter]
path = 'contracts/counter.clar'
clarity_version = 2
epoch = 2.4

[contracts.ifstatement]
path = 'contracts/ifstatement.clar'
clarity_version = 2
epoch = 2.4

[contracts.keywords]
path = 'contracts/keywords.clar'
clarity_version = 2
epoch = 2.4

[contracts.listtokens]
path = 'contracts/listtokens.clar'
clarity_version = 2
epoch = 2.4

[contracts.maps]
path = 'contracts/maps.clar'
clarity_version = 2
epoch = 2.4

[contracts.privatefunction]
path = 'contracts/privatefunction.clar'
clarity_version = 2
epoch = 2.4

[contracts.privatefunction1]
path = 'contracts/privatefunction1.clar'
clarity_version = 2
epoch = 2.4

[contracts.privatefunction2]
path = 'contracts/privatefunction2.clar'
clarity_version = 2
epoch = 2.4

[contracts.publicfunction]
path = 'contracts/publicfunction.clar'
clarity_version = 2
epoch = 2.4

[contracts.publicfunction1]
path = 'contracts/publicfunction1.clar'
clarity_version = 2
epoch = 2.4

[contracts.publicfunction2]
path = 'contracts/publicfunction2.clar'
clarity_version = 2
epoch = 2.4

[contracts.readonlyfunc]
path = 'contracts/readonlyfunc.clar'
clarity_version = 2
epoch = 2.4

[contracts.sequence]
path = 'contracts/sequence.clar'
clarity_version = 2
epoch = 2.4

[contracts.try]
path = 'contracts/try.clar'
clarity_version = 2
epoch = 2.4

[contracts.unwrap-flavor]
path = 'contracts/unwrap-flavor.clar'
clarity_version = 2
epoch = 2.4

[contracts.variable]
path = 'contracts/variable.clar'
clarity_version = 2
epoch = 2.4

[repl]
clarity_wasm_mode = false
show_timings = false

[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
